export const G2_PCM_SAMPLE_RATE_HZ = 16_000
export const G2_PCM_CHANNEL_COUNT = 1
export const G2_PCM_BYTES_PER_SAMPLE = 2
export const G2_PCM_BYTES_PER_SECOND =
  G2_PCM_SAMPLE_RATE_HZ * G2_PCM_CHANNEL_COUNT * G2_PCM_BYTES_PER_SAMPLE
